version: '3'

volumes:
  node_modules:

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - 8080:8080
